nextcloud:
    host: ENC[AES256_GCM,data:fGELTm/Na+JTMR7svpLfdC19kiv74ZCj,iv:9Fs3lW6PuFYnlf2+/A/iOEtk39np+oO/ldhv/QGdWGY=,tag:YrE9vJCNpX3s2TEoO1724w==,type:str]
    username: ENC[AES256_GCM,data:cmQ1yWoE8Q==,iv:uHGoeieO2s0+61hkQ4CCWWqLzrAcMr1C9OJDYO+P2qs=,tag:V0CGO5ZPqJz8w12m2aADZw==,type:str]
    password: ENC[AES256_GCM,data:q+AkktAzywMhERJlLVk=,iv:f5xi53N+6Cg4DWCz3X9Pv48A5FYABoeYBi8FMMpCCUI=,tag:ntlKwmh5K7rBjrSxofcC4w==,type:str]
    email: ENC[AES256_GCM,data:CKUMnJH+WGRjpyEaWhFiRKwY7bz86g==,iv:zsTZ1fb4pe3CPS/lTCE8y9DxKMS3WxwGETP1+XrNYAg=,tag:Vb41yjYatiLuu4SKxEKR5g==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:28hZaA==,iv:vHRYY/UHk2FhOlN1TixBUOTDC5TcKnNyW5q+eEPVrEM=,tag:ee5wWu3+IVaYw/OaDOIfMg==,type:bool]
    className: ENC[AES256_GCM,data:XAtj3ebnfA==,iv:/jsFN3NVvzNQU4lGWAHQCQFevESnpDTrjY/vYlUd4Mw=,tag:GlwnQ5BnlHCw1y5JArmeJA==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:78uqLqs3MldvFyam6h6x+CNYSO0ORyvU,iv:YPB6K7iDST+2cnDupVUB12C/42Out1Sdbd3L5WgOrF4=,tag:6VlSTUCcxAAxyRfENcq1iA==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:Og==,iv:mLGCT3FvPpDX07v1edKWrYacMOH8lIW/0YF+J5+kjik=,tag:HM8nwuu5eb0rNdlGV1cNiA==,type:str]
              pathType: ENC[AES256_GCM,data:iFOb9f5b,iv:UzdvuyBZYtCgVWqVofKjrYQkeLSYmOnvXn4DYrp8xgg=,tag:j1v22ZJNBo6lkg63v9UKGA==,type:str]
    #ENC[AES256_GCM,data:ZdzndWoa54mZMRnfFBopNhIwhRtIcIXqfF7JbCuoCAyp/6fw9MvG4lIs9BntXTwfloo3W97oASPKhiNqHQ==,iv:03Kmc2+nxt+e6eb3Iu3XUFkqTg3ZEVsvAQALTogIjbo=,tag:Pi8r+frdmSL3p6vnGPYEFQ==,type:comment]
    tls: []
internalDatabase:
    enabled: ENC[AES256_GCM,data:Da8bUHE=,iv:UtSRyl+o7r0xiTKDpbfhvTnm7chADT4caSzAGyDMJp0=,tag:4nhLNs0Y4ceuP9/IaFpLTw==,type:bool]
mariadb:
    enabled: ENC[AES256_GCM,data:6k+kXx4=,iv:8D70baEJMqjw/Yow6csNb4ImTfgjsKFQiO9l/4dbxB0=,tag:jxjnBgcX/lKWx3M2XrpmQg==,type:bool]
postgresql:
    enabled: ENC[AES256_GCM,data:PB7xRSc=,iv:1X3Mty6YEVo3dko8N2LcrDcnTUGmrbGk0nR6zYzxCic=,tag:Gd9UBF40hZII9Pyg4nsFow==,type:bool]
externalDatabase:
    enabled: ENC[AES256_GCM,data:N25IZQ==,iv:Wx+W/aJaWtk0J5VL8z/Kf/dX332BysbkxJJt1RkMNYw=,tag:gcgn3tbFOeJs+ER01JOGHQ==,type:bool]
    type: ENC[AES256_GCM,data:AGypQp6dQdf2eg==,iv:RJwlSPt5/g68/ohZkCwvufglz0oPa6d+bZP8VSWwLsY=,tag:5dmc7n2Eu+2hs7AOwrrZaw==,type:str]
    host: ENC[AES256_GCM,data:6+PosWu5yN9QQr9RmIaEoGjkrwXKh8zd4C9t8T//T8uxlHmAOYs=,iv:x86+5b7zJdtzsL1XuekKi4QcalOGuCZ6xCTRhpCgFQY=,tag:hCLokTXDv/c2fCVmdk/tAw==,type:str]
    port: ENC[AES256_GCM,data:5svLpA==,iv:DwItjh5usom5HoFP88TS7hCrswWPjQakY2flefp2L7Y=,tag:tL6uw02ObsOaoURcUm9Viw==,type:int]
    database: ENC[AES256_GCM,data:4Mw8TGUXAGPYNgSAYek=,iv:a5UH9l6SB7VB3DcedxnKpPD2mLbuWty/PtNWDIJybwA=,tag:Gi/eMwpvF0E6gPLvxoA6sQ==,type:str]
    user: ENC[AES256_GCM,data:3m+77Lv91Zt2IA==,iv:BQL9AStxUci8qRDGRR0nxPJM0ekzyXXCPuQhuuSmoWI=,tag:ffrYMf/d4SrRxAguR0GZJA==,type:str]
    password: ""
    existingSecret:
        enabled: ENC[AES256_GCM,data:KBvM+A==,iv:2fKrxk+LGjJ11jH4IHCG2oqQlBaTP8bvEOAj9ZcrUu4=,tag:VLxSLNvsRmOWCxNCNdEuBQ==,type:bool]
        secretName: ENC[AES256_GCM,data:ErwlQkqkXxrpYLj3rEzeyJV3EQ==,iv:ZXg/f6B+KzPtdBBB1LnmuchBKX2M2wKduuXd7Dt1VA8=,tag:PjC5G5qsP+bkZrJDb5dXtA==,type:str]
        usernameKey: ENC[AES256_GCM,data:sjMkT0221ig=,iv:YhQYVEWBUiJ/DlpKgNMmw+9p95/iu+MWbil2K0M2Jvg=,tag:DTroyO+r4UoBT1edWTQhSw==,type:str]
        passwordKey: ENC[AES256_GCM,data:FfENoVUYKGc=,iv:nizlCqY45vawmbgsd7seQ3eUkz1916VCx/0rThCXxO4=,tag:dLIGDdEcVZ9Mqd3XHWfNTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19dr2laukg526wv798hn8phwkhch0nwxszj57lrrncww2lghqeptsap89fl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxc0VYTUFvVThKd1dCdUgy
            djhPdXRkYU5yNFVPdFdKWHZSTDV0aElvbWdFCkRJL0JJK2daYU1hNGljMmVBcEI0
            T3JlWVlHSnlHYXIwNXI2eUdVa2tGNFkKLS0tIGVVTVd3c1gxbjcvcG1OLzFXTDRr
            K1pFRW5keHNLSzYvR1l5bXp1QVdJbFkKUZJIwE7agYL4G64TBPwWWU7uyQoxFOdl
            4A+spYVAsPC2SSVgFZehQtNMFWT1k6jNR4XPgosD2KQBoDJ9HCttpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T10:06:56Z"
    mac: ENC[AES256_GCM,data:RqmTZNwhqo4uXFjGKUbyJUhE9/esvgRzVnbEBIhKh9L5ZhDdsgdMc/K9YZJjSGSymvC2/RW/hrvIUK6PpDCjF4WwDUjVqbdcqepxctLm3X32ZYeqJWhS6wDIMAPXaSBhPveOAyxZ5Dvm7t6vIr/nBkbn+T5orySLqweCH29NaZE=,iv:nR4mwWOIjiSC4ii/f9gyF/uInP7ax82fM8Ar/qyUD/c=,tag:6CDKl+QNCnrsHgkoa8TDew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
