nextcloud:
    host: ENC[AES256_GCM,data:oseFBWIgAPK29bttEroE8NEqVnZwSen8,iv:nsX8z2eS4JXlTbbI3dbMqU4cQjL5ngvkI80q7MXL2NY=,tag:SSo3YYTkzejHsFttXeBuAA==,type:str]
    username: ENC[AES256_GCM,data:LdGPVw==,iv:9ks8o1zab8GVnQq8/ZkvC2xJE9lKhLPTjq9TtNbBYrU=,tag:pXcE6b+5Aj4lUbZMm892AQ==,type:str]
    #ENC[AES256_GCM,data:DRl0H6MgQyLpYeaZ2eZnQRcKF05nb0S/GzU=,iv:70acXFZe2B8MPcMrNZE7lNbTJdtSvMV63t9RkfQmRLc=,tag:DG6oMECusOPsOjiuWoN9PQ==,type:comment]
    password: ENC[AES256_GCM,data:c7tdMlEc/6JPq5nX/O9Z,iv:qiEl8aXV7TEXBgCQVvdnhP6zm1VcGyOZuazs1PTEOco=,tag:PLw2kmrjmr87su/lN7N4gQ==,type:str]
    dataDir: ENC[AES256_GCM,data:eRHNn7Gf4EA3LjBdhnKwUDAm,iv:mtLa4zDODBf4TEXonlHCo+SBiEG82iiQSLws2aw0Aog=,tag:kU+0mtAhMn/NsDAPZTCCvA==,type:str]
    trustedDomains:
        - ENC[AES256_GCM,data:ODeiQ0DsixQGrc+lD0aiMTAPQZcEEagz,iv:OFm/p4Pbcr7hh8aNK8w8D11fkH6udru7V9rFs/CNSZA=,tag:vBhFZha7+Tcg3R0H3Q6lsQ==,type:str]
        - ENC[AES256_GCM,data:zii6/MkyhayD6Ddyug==,iv:38UxIYX9j9UL6PpmVon5q2iCKObzwC3wBb+s4wH4mXs=,tag:Oaa0OLTeYNK6SOLh7vPOaQ==,type:str]
internalDatabase:
    enabled: ENC[AES256_GCM,data:IUf0Iik=,iv:sFKGcsjYPS8sXsEYG56N0hdAx0/P4H1EP62H9bsCxXk=,tag:OI2KfO6FJv1gQPBEno5E6A==,type:bool]
mariadb:
    enabled: ENC[AES256_GCM,data:SFNJE1w=,iv:/Se2dYIv5p/SiJirakPW5zsuzSfpcoJyIZ5AyR/DORE=,tag:Ba93M8chF9SIU7HeOHP8Yg==,type:bool]
externalDatabase:
    enabled: ENC[AES256_GCM,data:GtnB+w==,iv:YT/KPfsEz4PDJS40tHUj21z72OnNRoCP5XmEp8M8wZg=,tag:q91g/ExDpbdxtCeX4gQt6Q==,type:bool]
    type: ENC[AES256_GCM,data:Y/fVxGil/zLzFg==,iv:Aemo8AmODs6+vOGhHQLz33D4Iw30DL6wS4sAa/eyZC4=,tag:xc+5gB7S8uufryQtMF1I3Q==,type:str]
    host: ENC[AES256_GCM,data:nAtmCfAxwJ+AG8IB2bxnqjJLLstNHJQRyWiteyy+JHqLgBOL,iv:KaoGHt123cDQFm75+mF0XMOEBNStZJsnfkPQfQM4xc8=,tag:VqcmtNtQYbmGu/9SbGcf9w==,type:str]
    port: ENC[AES256_GCM,data:xjU98A==,iv:IlCyA/yvd3D/gHtujte9tSm9OLPu+cPnaTuIprPOw24=,tag:2R0UFAgkfQGjpNxr2VQtcA==,type:int]
    database: ENC[AES256_GCM,data:jVKnL29ZqFuHRsnt2MM=,iv:NtY9svmzemkQmIGZWOdlT+QBl6UF4ruLQ324AtSr2RU=,tag:eWgnqaJVcMsrT5TekUnAGw==,type:str]
    user: ENC[AES256_GCM,data:xf7HKNe2Xb9s0A==,iv:n1tUwckupzYyNOIJvQHBYDn5v0GPr80tEeX2wuTypB0=,tag:WFAioW6jYS8/MVSu+CAAyw==,type:str]
    #ENC[AES256_GCM,data:dVgFYpWY7/Pllxoeu9VtcytMIRsOgiVVqLMR,iv:prU1v52XJ8EUt5orah12ifhdWhdOUIlKKohPTD4WfkM=,tag:dBHktwbsE/ckZ/E7z3szJw==,type:comment]
    password: ENC[AES256_GCM,data:f78gJN7uslXlshtzs08E,iv:6GXWGPL50PYymYz6DQ9k0VdnsNlL8eoknZAmGramS18=,tag:SQSGCvI2vJ8o0oLbLh1iRA==,type:str]
persistence:
    enabled: ENC[AES256_GCM,data:IBApFQ==,iv:aLt0lMKYikBPAYL7uqD5X/KraIlGhFEyP45wgxjW/20=,tag:pB8VWLZ3pbJsC4ySMO5uMw==,type:bool]
    accessMode: ENC[AES256_GCM,data:KqGzQhpq+Q9nkunnRg==,iv:7A5yRChVEQwA7xXydTqIxknDp49DZ/LXiF5HItEG6Jw=,tag:1AsNj6BSX+bDI5x5LXMq8w==,type:str]
    size: ENC[AES256_GCM,data:mYVcTA==,iv:5eBZtJdf7nPwa3cSdK/8lsq45d/MSvOlGQ15IbtcUcg=,tag:UT1MqETwgjad4QFTP16Tqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19dr2laukg526wv798hn8phwkhch0nwxszj57lrrncww2lghqeptsap89fl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT29GVEVaNkVLcGVJZ2pv
            T20xeFNYcXB5MHBCVExiZXM4OG9UTjhMQmlJCkJzeXV6OW9lVkJOYXhqUS9kYjJz
            Z3FTVm1xaGd3cVhQVWtBRGNDcnRtZGcKLS0tIFpFRWlSRmtsRkl2eC8xeFlnZTd1
            ZGtIdHlKRk5GTHNEY2JRY2I3dkRpSE0KFttKSVV0pslkEMQ5+vbEIa1PbmWVzOTQ
            aqLfJeuzIdUWsdV4mSrzQePXjXNmmBWznbzsvpZUXjcTPa9W8nqkIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T00:16:48Z"
    mac: ENC[AES256_GCM,data:z8gux4C7runjoJT/7COA0a9hxkhW+0nFWgLF8YCY5aa0fIs3Lx7kiOXDetVjolBdMeezbv+pXIRfXqVSv2PILUbbMiA1E0g00jzei32+GsOtk7adW+WTu5fw09zIescTb96g8ooZdnsXFrV5r3+zh9WotCDMSONN0VHyEaLB9JY=,iv:gRhygn9Dl+86cVyYX+Li6W3+NpiRlqMa7qaJ/HKREuA=,tag:gwaOektfo81CJL/EMVFKpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
