apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-atm10-pv
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: uranus-minecraft
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/minecraft/atm10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-atm10-pvc
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: uranus-minecraft
  resources:
    requests:
      storage: 80Gi
