apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-credentials
  namespace: homelab-apps
type: Opaque
stringData:
  POSTGRES_DB: "${DB_NAME}"
  POSTGRES_USER: "${DB_USER}"
  POSTGRES_PASSWORD: "${DB_PASSWORD}"
